spring.application.name=professionalService
server.port=${SERVER_PORT:8085}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/professional_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:professional_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:professional_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
