server:
  port: 8081

spring:
  application:
    name: patient-service

  datasource:
    url: jdbc:postgresql://localhost:5433/patient_db
    username: patient_user
    password: patient_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info